//! Inject configuration files into an unpacked rootfs directory.
//!
//! Prepares a rootfs for VM use by injecting:
//! - SSH `authorized_keys` so the host can connect to the guest
//! - `/etc/resolv.conf` for DNS resolution
//!
//! Called after OCI layer extraction and before ext4 image creation.

use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};

use crate::error::{Error, Result};

/// Common SSH public key filenames, in preference order.
const SSH_PUBKEY_NAMES: &[&str] = &[
    "id_ed25519.pub",
    "id_ecdsa.pub",
    "id_rsa.pub",
];

/// Return the default SSH public key path.
///
/// Looks in the invoking user's `~/.ssh/` directory for common key types.
/// When running under `sudo`, uses `SUDO_USER` to resolve the real user's
/// home directory instead of root's.
pub fn default_ssh_pubkey_path() -> Option<PathBuf> {
    let home = invoking_user_home()?;
    let ssh_dir = home.join(".ssh");
    SSH_PUBKEY_NAMES
        .iter()
        .map(|name| ssh_dir.join(name))
        .find(|p| p.exists())
}

/// Inject an SSH `authorized_keys` file into the rootfs.
///
/// Reads the public key from `pubkey_path` and writes it to
/// `/root/.ssh/authorized_keys` inside the rootfs. Permissions are
/// set to 700 for `.ssh/` and 600 for `authorized_keys` as required
/// by OpenSSH.
///
/// The SPEC says: "SSH key from config (default `~/.ssh/id_ed25519`),
/// injected into rootfs at image pull time." The caller passes the
/// `.pub` counterpart of the configured private key.
pub fn inject_ssh_authorized_keys(rootfs_dir: &Path, pubkey_path: &Path) -> Result<()> {
    let pubkey = fs::read_to_string(pubkey_path).map_err(|e| Error::Io {
        path: pubkey_path.to_path_buf(),
        source: e,
    })?;

    if pubkey.trim().is_empty() {
        return Err(Error::Image(format!(
            "SSH public key file is empty: {}",
            pubkey_path.display()
        )));
    }

    let ssh_dir = rootfs_dir.join("root/.ssh");
    fs::create_dir_all(&ssh_dir).map_err(|e| Error::Io {
        path: ssh_dir.clone(),
        source: e,
    })?;
    fs::set_permissions(&ssh_dir, fs::Permissions::from_mode(0o700)).map_err(|e| Error::Io {
        path: ssh_dir.clone(),
        source: e,
    })?;

    let authorized_keys_path = ssh_dir.join("authorized_keys");
    fs::write(&authorized_keys_path, pubkey.as_bytes()).map_err(|e| Error::Io {
        path: authorized_keys_path.clone(),
        source: e,
    })?;
    fs::set_permissions(
        &authorized_keys_path,
        fs::Permissions::from_mode(0o600),
    )
    .map_err(|e| Error::Io {
        path: authorized_keys_path,
        source: e,
    })?;

    Ok(())
}

/// Inject `/etc/resolv.conf` into the rootfs for DNS resolution.
///
/// Writes a `resolv.conf` with Cloudflare and Google public DNS servers.
/// If the rootfs already has a `resolv.conf` (possibly a symlink from the
/// container image, e.g. Ubuntu's link to `/run/systemd/resolve/...`),
/// it is removed first and replaced with a regular file.
pub fn inject_resolv_conf(rootfs_dir: &Path) -> Result<()> {
    let etc_dir = rootfs_dir.join("etc");
    fs::create_dir_all(&etc_dir).map_err(|e| Error::Io {
        path: etc_dir.clone(),
        source: e,
    })?;

    let resolv_path = etc_dir.join("resolv.conf");

    // Remove existing resolv.conf — may be a symlink in some container images.
    if resolv_path.symlink_metadata().is_ok() {
        let _ = fs::remove_file(&resolv_path);
    }

    let contents = "\
# Generated by ember
nameserver 1.1.1.1
nameserver 8.8.8.8
";

    fs::write(&resolv_path, contents).map_err(|e| Error::Io {
        path: resolv_path,
        source: e,
    })?;

    Ok(())
}

/// Resolve the invoking (non-root) user's home directory.
///
/// Under `sudo`, `HOME` is typically `/root`. We check `SUDO_USER` first
/// and look up that user's home via `getpwnam`. Falls back to `HOME`.
fn invoking_user_home() -> Option<PathBuf> {
    // Try SUDO_USER first (set by sudo to the original user).
    if let Ok(sudo_user) = std::env::var("SUDO_USER") {
        if let Some(home) = home_for_user(&sudo_user) {
            return Some(home);
        }
    }

    // Fall back to HOME.
    std::env::var_os("HOME").map(PathBuf::from)
}

/// Look up a user's home directory via getpwnam.
fn home_for_user(username: &str) -> Option<PathBuf> {
    use std::ffi::CString;
    let name = CString::new(username).ok()?;
    // SAFETY: getpwnam is passed a valid C string. The returned pointer
    // is to a static buffer — we copy the home_dir field immediately.
    let pw = unsafe { nix::libc::getpwnam(name.as_ptr()) };
    if pw.is_null() {
        return None;
    }
    let home_dir = unsafe { std::ffi::CStr::from_ptr((*pw).pw_dir) };
    Some(PathBuf::from(home_dir.to_string_lossy().into_owned()))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn inject_ssh_creates_authorized_keys() {
        let rootfs = tempfile::tempdir().unwrap();
        let keyfile = rootfs.path().join("test_key.pub");
        fs::write(&keyfile, "ssh-ed25519 AAAA... user@host\n").unwrap();

        inject_ssh_authorized_keys(rootfs.path(), &keyfile).unwrap();

        let ak = rootfs.path().join("root/.ssh/authorized_keys");
        assert!(ak.exists());
        assert_eq!(fs::read_to_string(&ak).unwrap(), "ssh-ed25519 AAAA... user@host\n");
    }

    #[test]
    fn inject_ssh_sets_permissions() {
        let rootfs = tempfile::tempdir().unwrap();
        let keyfile = rootfs.path().join("test_key.pub");
        fs::write(&keyfile, "ssh-ed25519 AAAA... user@host\n").unwrap();

        inject_ssh_authorized_keys(rootfs.path(), &keyfile).unwrap();

        let ssh_dir = rootfs.path().join("root/.ssh");
        let dir_mode = fs::metadata(&ssh_dir).unwrap().permissions().mode() & 0o777;
        assert_eq!(dir_mode, 0o700, "~/.ssh should be 700");

        let ak = ssh_dir.join("authorized_keys");
        let file_mode = fs::metadata(&ak).unwrap().permissions().mode() & 0o777;
        assert_eq!(file_mode, 0o600, "authorized_keys should be 600");
    }

    #[test]
    fn inject_ssh_empty_key_fails() {
        let rootfs = tempfile::tempdir().unwrap();
        let keyfile = rootfs.path().join("empty.pub");
        fs::write(&keyfile, "  \n").unwrap();

        let result = inject_ssh_authorized_keys(rootfs.path(), &keyfile);
        assert!(result.is_err());
    }

    #[test]
    fn inject_ssh_missing_key_fails() {
        let rootfs = tempfile::tempdir().unwrap();
        let result = inject_ssh_authorized_keys(rootfs.path(), Path::new("/nonexistent/key.pub"));
        assert!(result.is_err());
    }

    #[test]
    fn inject_ssh_existing_ssh_dir_is_ok() {
        let rootfs = tempfile::tempdir().unwrap();
        fs::create_dir_all(rootfs.path().join("root/.ssh")).unwrap();

        let keyfile = rootfs.path().join("test_key.pub");
        fs::write(&keyfile, "ssh-ed25519 AAAA... user@host\n").unwrap();

        inject_ssh_authorized_keys(rootfs.path(), &keyfile).unwrap();

        let ak = rootfs.path().join("root/.ssh/authorized_keys");
        assert!(ak.exists());
    }

    #[test]
    fn inject_resolv_conf_creates_file() {
        let rootfs = tempfile::tempdir().unwrap();
        fs::create_dir_all(rootfs.path().join("etc")).unwrap();

        inject_resolv_conf(rootfs.path()).unwrap();

        let resolv = rootfs.path().join("etc/resolv.conf");
        assert!(resolv.exists());

        let contents = fs::read_to_string(&resolv).unwrap();
        assert!(contents.contains("nameserver 1.1.1.1"));
        assert!(contents.contains("nameserver 8.8.8.8"));
    }

    #[test]
    fn inject_resolv_conf_creates_etc_dir() {
        let rootfs = tempfile::tempdir().unwrap();
        // No etc/ dir yet — inject should create it.
        inject_resolv_conf(rootfs.path()).unwrap();

        let resolv = rootfs.path().join("etc/resolv.conf");
        assert!(resolv.exists());
    }

    #[test]
    fn inject_resolv_conf_replaces_existing() {
        let rootfs = tempfile::tempdir().unwrap();
        let etc = rootfs.path().join("etc");
        fs::create_dir_all(&etc).unwrap();
        fs::write(etc.join("resolv.conf"), "old content").unwrap();

        inject_resolv_conf(rootfs.path()).unwrap();

        let contents = fs::read_to_string(etc.join("resolv.conf")).unwrap();
        assert!(contents.contains("nameserver 1.1.1.1"));
        assert!(!contents.contains("old content"));
    }

    #[cfg(unix)]
    #[test]
    fn inject_resolv_conf_replaces_symlink() {
        let rootfs = tempfile::tempdir().unwrap();
        let etc = rootfs.path().join("etc");
        fs::create_dir_all(&etc).unwrap();

        // Simulate Ubuntu's symlink: /etc/resolv.conf → /run/systemd/resolve/resolv.conf
        std::os::unix::fs::symlink("/run/systemd/resolve/resolv.conf", etc.join("resolv.conf"))
            .unwrap();

        inject_resolv_conf(rootfs.path()).unwrap();

        let resolv = etc.join("resolv.conf");
        assert!(!resolv.symlink_metadata().unwrap().is_symlink());
        let contents = fs::read_to_string(&resolv).unwrap();
        assert!(contents.contains("nameserver"));
    }

    #[test]
    fn invoking_user_home_returns_some() {
        // Should succeed unless HOME is unset.
        if std::env::var_os("HOME").is_some() {
            let home = invoking_user_home().unwrap();
            assert!(home.is_absolute());
        }
    }

    #[test]
    fn default_ssh_pubkey_finds_existing_key() {
        // Create a fake home with an ed25519 key.
        let fake_home = tempfile::tempdir().unwrap();
        let ssh_dir = fake_home.path().join(".ssh");
        fs::create_dir_all(&ssh_dir).unwrap();
        fs::write(ssh_dir.join("id_ed25519.pub"), "ssh-ed25519 AAAA...\n").unwrap();

        // Temporarily override HOME (no SUDO_USER in test).
        let orig = std::env::var_os("HOME");
        std::env::set_var("HOME", fake_home.path());
        // Remove SUDO_USER so we test the HOME fallback.
        let orig_sudo = std::env::var_os("SUDO_USER");
        std::env::remove_var("SUDO_USER");

        let path = default_ssh_pubkey_path();
        assert!(path.is_some());
        assert!(path.unwrap().to_string_lossy().ends_with("id_ed25519.pub"));

        // Restore.
        if let Some(h) = orig {
            std::env::set_var("HOME", h);
        }
        if let Some(s) = orig_sudo {
            std::env::set_var("SUDO_USER", s);
        }
    }

    #[test]
    fn default_ssh_pubkey_tries_rsa_fallback() {
        let fake_home = tempfile::tempdir().unwrap();
        let ssh_dir = fake_home.path().join(".ssh");
        fs::create_dir_all(&ssh_dir).unwrap();
        // Only RSA key exists.
        fs::write(ssh_dir.join("id_rsa.pub"), "ssh-rsa AAAA...\n").unwrap();

        let orig = std::env::var_os("HOME");
        std::env::set_var("HOME", fake_home.path());
        let orig_sudo = std::env::var_os("SUDO_USER");
        std::env::remove_var("SUDO_USER");

        let path = default_ssh_pubkey_path();
        assert!(path.is_some());
        assert!(path.unwrap().to_string_lossy().ends_with("id_rsa.pub"));

        if let Some(h) = orig {
            std::env::set_var("HOME", h);
        }
        if let Some(s) = orig_sudo {
            std::env::set_var("SUDO_USER", s);
        }
    }

    #[test]
    fn default_ssh_pubkey_returns_none_when_no_keys() {
        let fake_home = tempfile::tempdir().unwrap();
        let ssh_dir = fake_home.path().join(".ssh");
        fs::create_dir_all(&ssh_dir).unwrap();
        // No key files.

        let orig = std::env::var_os("HOME");
        std::env::set_var("HOME", fake_home.path());
        let orig_sudo = std::env::var_os("SUDO_USER");
        std::env::remove_var("SUDO_USER");

        let path = default_ssh_pubkey_path();
        assert!(path.is_none());

        if let Some(h) = orig {
            std::env::set_var("HOME", h);
        }
        if let Some(s) = orig_sudo {
            std::env::set_var("SUDO_USER", s);
        }
    }
}
